---
title: "DecisionTreeFinalProject"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rio)
library(plyr)
library(tidyverse)
library(rpart)
library(psych)
library(pROC)
library(rpart.plot)
library(rattle)
library(caret)
library(C50)
library(mlbench)
library(e1071)
```

# Data Cleaning

```{r}
stroke <- read.csv("stroke.csv")
stroke$bmi <- gsub("N/A", NA, stroke$bmi)
stroke$smoking_status <- gsub("Unknown", NA, stroke$smoking_status)
stroke <- na.omit(stroke)

# Data Cleaning Specifically for Decision Tree - Changing things to Binary 

stroke$bmi <- as.numeric(stroke$bmi)
stroke <- stroke %>%
  mutate(bmi_state = ifelse(bmi <= 25, "normal", "overweight"))

# https://www.cdc.gov/healthyweight/assessing/bmi/adult_bmi/index.html

stroke <- stroke %>%
  mutate(glucose_state = ifelse(avg_glucose_level <= 125, "normal", "diabetic"))

stroke <- stroke %>%
  mutate(age_state = ifelse(age <= 38.4, "young", "old"))

# https://www.statista.com/statistics/241494/median-age-of-the-us-population/#:~:text=In%202018%2C%20the%20median%20age,United%20States%20was%2038.4%20years.


stroke_positive <- subset(stroke, stroke == 1)
stroke_negative <- subset(stroke, stroke == 0)
set.seed(1980)
stroke_sample <- stroke_negative[sample(1:nrow(stroke_negative), size = 180),]
stroke_final <- rbind(stroke_sample, stroke_positive)
stroke_final <- stroke_final[-c(1, 2, 3, 7, 9, 10, 11)]

stroke_final <- lapply(stroke_final, function(x) as.factor(x))

stroke_final <- as_tibble(stroke_final)


```
# Creation of Test Set

```{r}
set.seed(1980)
stroke_break <- createDataPartition(stroke_final$stroke, times = 1, p = 0.8, list = FALSE)
training_stroke <- stroke_final[stroke_break,]
test_stroke <- stroke_final[-stroke_break,]

```

# Baserate Calculation for Stroke
```{r}
mean(as.numeric(stroke_final$stroke))-1

# 0.5
```

# Building the Model
```{r}
set.seed(1950)
tree_stroke = rpart(stroke~.,  
                            method = "class",
                            parms = list(split = "gini"),
                            data = training_stroke,
                            control = rpart.control(cp=0.01))


```

```{r}
tree_stroke
tree_stroke$variable.importance
```

```{r}
rpart.plot(tree_stroke, type = 4, extra = 101)
plotcp(tree_stroke)

stroke_predict = predict(tree_stroke, test_stroke, type = "class")
```

# Confusion Matrix 
```{r}
tree_matrix <- confusionMatrix(as.factor(stroke_predict), as.factor(test_stroke$stroke), positive = "1", dnn = c("Prediction", "Actual"), mode = "sens_spec")

tree_matrix
```

# Evaluation Metrics
```{r}
stroke_prob <- predict(tree_stroke, newdata = test_stroke, type = "prob")
stroke_prob <- as.tibble(stroke_prob)
stroke_eval <- data.frame(pred_class = stroke_predict, pred_prob = stroke_prob$`1`, target = as.numeric(test_stroke$stroke))
LogLoss(as.numeric(stroke_eval$pred_prob), as.numeric(test_stroke$stroke)) # 2.223

F1_Score(as.numeric(stroke_eval$pred_class), as.numeric(test_stroke$stroke)) 
# 0.5483871
```

# ROC Curve
```{r}
Stroke_roc <- roc(as.numeric(test_stroke$stroke), as.numeric(stroke_predict), plot = TRUE)
Stroke_roc$auc
plot(Stroke_roc) 
```

